require:
  - rubocop-rails
  - rubocop-fjord
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/migrate/20241226023120_create_active_storage_tables.active_storage.rb'


Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/20241226023120_create_active_storage_tables.active_storage.rb'
